name: REST DTO CI Build

on:
  push:
    branches: [ main ]
    paths:
    - DataTransferObjects/**
    - .github/workflows/rest-dto.yml
  pull_request:
    branches: [ main ]
    paths:
    - DataTransferObjects/**
    - .github/workflows/rest-dto.yml
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        include-prerelease: True
    - name: Restore dependencies
      run: dotnet restore
      working-directory: DataTransferObjects
    - name: Build
      run: dotnet build --no-restore
      working-directory: DataTransferObjects
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: DataTransferObjects
